name: Publish Npm Package

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: 安装依赖
        run: npm ci

      - name: 更新版本 & build
        run: |
          npm run version
          npm run build

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "::set-output name=changed::true"

      - name: 发布
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config user.name "wuguohao"
          git config user.email "1543922073@qq.com"
          npm whoami
          git add .
          git commit -m "update"
          git push 
          npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
